version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/12/main
    environment:
      - POSTGRES_DB=TerraformBuilder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/TerraformBuilder
    ports:
      - "8000:8000"
    depends_on:
      - db